### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'scope' in undefined

### ISSUE THREAD

**Issue by ImBIOS** [pmndrs/swc-jotai#2]
# 📜 Description
![image](https://user-images.githubusercontent.com/41441643/202149478-0d81e9c5-696c-4945-8e6e-fe3c0442b18b.png)

The experimental feature in Next.js with one or both plugins introduces an error like the screenshot above.

# 💻 System Information

next: ^13.0.2,
next-pwa: ^5.6.0,
jotai: 1.9.2,
swc-jotai/debug-label: 0.0.6,
swc-jotai/react-refresh: 0.0.2,
node v18.12.0
yarn v1.22.19
Windows 11 21H2 via WSL2 (Ubuntu 22.04.1 LTS)

# 🔃 How to Reproduce

1. Install all of the required packages above `yarn add ...`
2. Configure the `next.config.js` to enable the SWC Experimental Plugin feature
3. Run it with `yarn dev`
4. Voila! 💨 The project was working fine without the swc-jotai, but it now shows this error.

Codesandbox: [ImBIOS/next-swc-jotai-plugin-bug-lab](https://codesandbox.io/p/github/ImBIOS/next-swc-jotai-plugin-bug-lab/csb-5h5yoj/draft/naughty-merkle?file=%2FREADME.md)

# 👋 Need Help!
Is there any other information that can help debug this issue? Please let me know in the comment below.

**Comment by Thisen** [comment]
> Is there any other information that can help debug this issue?
Please provide a reproduction 🙏🏼

**Comment by ImBIOS** [comment]
> @ImBIOS Please provide a reproduction 🙏🏼

@Thisen, I've updated the issue description. Is there any other way I can help to debug it? I wonder if it is just my error or if the unstable library is the problem.

**Comment by Thisen** [comment]
> > @ImBIOS Please provide a reproduction 🙏🏼
> 
> @Thisen, I've updated the issue description. Is there any other way I can help to debug it? I wonder if it is just my error or if the unstable library is the problem.

Can you provide a Codesandbox?

**Comment by ImBIOS** [comment]
> @ImBIOS Can you provide a Codesandbox?

Here is the [Codesandbox link](https://codesandbox.io/p/github/ImBIOS/next-swc-jotai-plugin-bug-lab/csb-5h5yoj/draft/naughty-merkle?file=%2FREADME.md)

**Comment by Thisen** [comment]
> > @ImBIOS Can you provide a Codesandbox?
> 
> Here is the [Codesandbox link](https://codesandbox.io/p/github/ImBIOS/next-swc-jotai-plugin-bug-lab/csb-5h5yoj/draft/naughty-merkle?file=%2FREADME.md)

I can't access the Codesandbox, something wrong with the instance. Can you resolve it?

**Comment by ImBIOS** [comment]
> I can't access the Codesandbox, something wrong with the instance. Can you resolve it?

![image](https://user-images.githubusercontent.com/41441643/211726139-766d6525-e43c-4c3b-9e2d-090685cb4d9a.png)

@Thisen I've tried to access it through both Incognito and Signed-In, and it's successfully reproduced the error. I need more information to know what is happening on your side, like a Screenshot.

**Comment by Thisen** [comment]
> > I can't access the Codesandbox, something wrong with the instance. Can you resolve it?
> 
> ![image](https://user-images.githubusercontent.com/41441643/211726139-766d6525-e43c-4c3b-9e2d-090685cb4d9a.png)
> 
> @Thisen I've tried to access it through both Incognito and Signed-In, and it's successfully reproduced the error. I need more information to know what is happening on your side, like a Screenshot.

Works now, thanks!

**Comment by Thisen** [comment]
This should be fixed in `@swc-jotai/react-refresh@0.0.3`.

Please re-open if that's not the case.

**Comment by ImBIOS** [comment]
It is still not fixed. I have updated the project repository and codesandbox for anyone to reproduce this error.
